### PR TITLE
Support for Bootstrap v5

### PR DESCRIPTION
**Pull request by DionPotkamp**
Bootstrap 5 is out of beta and has some real improvements for forms. 

Hereby the bootstrap 5 version of laravel-form-components including floating labels.
 
image

With bootstrap 5 `form-group` has been removed. It's still a component because it can be used for inline radio's and check boxes with validation. 

`prepend` and `append` are also removed. This is replaced by `input-group` and can contain basically anything (just text, but also buttons and radio's). 

Read more here: [Bootstrap 5 migration: Forms](https://getbootstrap.com/docs/5.0/migration/#forms)

This has also been covered in the readme.

Closes: #50

### CODE REVIEW

**Comment by mustafa-online** [comment]
Can't wait for this to be merged 😍✨ thanks a lot @DionPotkamp

**Review by simtabi — CHANGES_REQUESTED** [review]
Please merge for bootstrap 5 support

**Comment by freezy-sk** [comment]
@pascalbaljet please merge this 🙏🏻

**Review by freezy-sk — APPROVED** [review]

**Comment by ArtMin96** [comment]
Any news?

**Comment by freezy-sk** [comment]
until this PR will be merged, you can use it by adding forked repository to your composer.json and requiring this pull requested branch.

`composer.json`
```
    "require": {
        ...
        "protonemedia/laravel-form-components": "dev-bootstrap-v5",
        ...
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:DionPotkamp/laravel-form-components.git"
        }
    ],
```

**Comment by pascalbaljet** [comment]
Hey everybody! I'll take a look at this PR as soon as possible, hopefully within a week. I was a bit preoccupied with the other projects 😅

**Comment by mustafa-online** [comment]
@pascalbaljet 
any progress on this? 😢

**Comment by pascalbaljet** [comment]
I just tagged v3 with support for Bootstrap 5. Special thanks to @DionPotkamp for this PR!

**Comment by freezy-sk** [comment]
@pascalbaljet please release it as 2.6.0
it's not breaking changes so according to semantic versioning there is not need to increment major version

**Pull request merged**
